// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzcffZLzqGwi_CSrERm9ni4NAdZ2GzyW4',
    appId: '1:1033318110155:web:6542a10219ecad8617dc4e',
    messagingSenderId: '1033318110155',
    projectId: 'baytarapp',
    authDomain: 'baytarapp.firebaseapp.com',
    storageBucket: 'baytarapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiLp-aa5ZGP_LcL68raHmswAQw4Ll0bio',
    appId: '1:1033318110155:android:80b487e553ae793d17dc4e',
    messagingSenderId: '1033318110155',
    projectId: 'baytarapp',
    storageBucket: 'baytarapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPEBAVsma6ge_prpDldq5IpigMTYLWLjs',
    appId: '1:1033318110155:ios:f6810099caae9dcb17dc4e',
    messagingSenderId: '1033318110155',
    projectId: 'baytarapp',
    storageBucket: 'baytarapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPEBAVsma6ge_prpDldq5IpigMTYLWLjs',
    appId: '1:1033318110155:ios:f6810099caae9dcb17dc4e',
    messagingSenderId: '1033318110155',
    projectId: 'baytarapp',
    storageBucket: 'baytarapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzcffZLzqGwi_CSrERm9ni4NAdZ2GzyW4',
    appId: '1:1033318110155:web:0d816f5f7ca8bb8b17dc4e',
    messagingSenderId: '1033318110155',
    projectId: 'baytarapp',
    authDomain: 'baytarapp.firebaseapp.com',
    storageBucket: 'baytarapp.firebasestorage.app',
  );
}
